server:
  port: 8092
  servlet:
    context-path: /property-view
spring:
  application:
    name: GpSolutionsTechTask
  datasource:
    url: jdbc:h2:mem:gptechtask
    username: admin
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    default-schema: public