server:
  port: 8092
  servlet:
    context-path: /property-view
spring:
  application:
    name: GpSolutionsTechTask
  datasource:
    url: jdbc:postgresql://localhost:5432/gptechtask
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    default-schema: public